let found: boolean = true;
let grade: number = 88.5;
let firstName: string = "islam";
let lastName: string = 'mostafa';
let age: number=29;
let familyName:string ="islam mostafa elgebally";
let isValid:boolean=true;
let isValidTwo:boolean=false;
console.log(`${isValid}  ${isValidTwo}`);
console.log(found);
console.log("grade is" + grade);
console.log("HI" + firstName + " " + lastName);
console.log(`Hi ${firstName} ${lastName}`);
